---
title: Fart Sounds Podcast
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hi@john.design
description: Fart Sounds Podcast
baseurl: 
url: http://fartsounds.show
post_dirs: false
host: jchoura-mbp.local
port: 4444
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
