---
title: Fart Sounds Podcast
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    title: 
    permalink: "/:title/"
    layout: post
    episode: 
    duration: 
    soundcloud_id: 
    gplay_share: 
    soundcloud_share: 
email: hi@john.design
description: Fart Sounds with John Choura, The Podcast
baseurl: 
permalink: pretty
url: http://fartsounds.show
post_dirs: false
host: jchoura-mbp.local
port: 4444
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
